// Generated by CoffeeScript 1.7.1

/*
  index.coffee
  https://github.com/maurofranceschini/zigbee-abstraction-layer

  (C) 2014-2014 Mauro Franceschini
  Released under Apache 2 License.
 */

(function() {
  module.exports = {
    ClearDeviceKeyPairSet: {
      Request: require("./clear-device-key-pair-set-request"),
      Confirm: require("./clear-device-key-pair-set-confirm")
    },
    ConfirmId: {
      Report: require("./confirm-id-report")
    },
    DataFragment: {
      Request: require("./data-fragment-request"),
      Indication: require("./data-fragment-indication")
    },
    DeregisterEndpoint: {
      Request: require("./deregister-endpoint-request"),
      Confirm: require("./deregister-endpoint-confirm")
    }
  };

}).call(this);

//# sourceMappingURL=index.map
